"""AAFP Commons public API."""

from aafp_commons.adoption import (
    ADOPTION_BOUNDARY,
    ADOPTION_DECISION_SCHEMA,
    ADOPTION_REQUEST_SCHEMA,
    AdoptionDecisionNotFoundError,
    AdoptionRequestError,
    AdoptionRequestIntegrityError,
    ConstitutionAdoptionDecision,
    ConstitutionAdoptionRequest,
    FileAdoptionDecisionStore,
    FileAdoptionRequestStore,
)
from aafp_commons.constitutions import (
    ConstitutionError,
    ConstitutionGuidance,
    ConstitutionIntegrityError,
    ConstitutionManifest,
    ConstitutionNotFoundError,
    ConstitutionResolver,
    ConstitutionSource,
    FileConstitutionResolver,
    ProviderConstraint,
    RuntimeCompatibility,
    constraints_by_precedence,
    merge_constraints,
    version_key,
)
from aafp_commons.discovery import ConstitutionCatalog, ConstitutionSummary
from aafp_commons.handshake import (
    HANDSHAKE_BOUNDARY,
    HANDSHAKE_SCHEMA,
    FileHandshakeStore,
    HandshakeError,
    HandshakeIntegrityError,
    RuntimeHandshake,
)
from aafp_commons.identity import derive_agent_id
from aafp_commons.index import PublicResearchIndex, ResearchIndexBackend
from aafp_commons.join import AgentJoinSession
from aafp_commons.ledger import Ledger
from aafp_commons.models import (
    ConstitutionRef,
    EvidenceRef,
    KnowledgePacket,
    MethodRef,
)
from aafp_commons.packages import (
    ConstitutionPackage,
    ConstitutionPackageError,
    ConstitutionPackageNotFoundError,
    ConstitutionPackageRegistry,
    default_registry,
)
from aafp_commons.protocols import ProtocolNotFoundError, load_schema, protocol_ids, schema_path
from aafp_commons.publication import (
    PUBLICATION_SCHEMA,
    PUBLICATION_STATE_SCHEMA,
    PublicationBackend,
    PublicationService,
)
from aafp_commons.repository import CommonsRepository
from aafp_commons.sharing import (
    export_public_snapshot,
    import_public_snapshot,
    load_public_snapshot,
    search_public_snapshot,
)
from aafp_commons.signing import SignedPacket, sign_packet
from aafp_commons.transport import (
    ADOPTION_CAPABILITY,
    ADOPTION_ENVELOPE_SCHEMA,
    HANDSHAKE_CAPABILITY,
    HANDSHAKE_ENVELOPE_SCHEMA,
    AafpConstitutionTransport,
    AafpJoinTransport,
    AafpPacketTransport,
    AafpRuntimeHandshakeTransport,
    AafpTransportProtocolError,
    AafpTransportUnavailable,
    decode_adoption_request,
    decode_runtime_handshake,
    encode_adoption_request,
    encode_runtime_handshake,
)

__all__ = [
    "ADOPTION_BOUNDARY",
    "ADOPTION_DECISION_SCHEMA",
    "ADOPTION_CAPABILITY",
    "ADOPTION_ENVELOPE_SCHEMA",
    "HANDSHAKE_CAPABILITY",
    "HANDSHAKE_ENVELOPE_SCHEMA",
    "ADOPTION_REQUEST_SCHEMA",
    "AdoptionRequestError",
    "AdoptionRequestIntegrityError",
    "AdoptionDecisionNotFoundError",
    "CommonsRepository",
    "AgentJoinSession",
    "ConstitutionAdoptionRequest",
    "ConstitutionAdoptionDecision",
    "FileAdoptionDecisionStore",
    "FileAdoptionRequestStore",
    "AafpConstitutionTransport",
    "AafpJoinTransport",
    "AafpPacketTransport",
    "AafpRuntimeHandshakeTransport",
    "AafpTransportUnavailable",
    "AafpTransportProtocolError",
    "ConstitutionCatalog",
    "HANDSHAKE_BOUNDARY",
    "HANDSHAKE_SCHEMA",
    "FileHandshakeStore",
    "HandshakeError",
    "HandshakeIntegrityError",
    "RuntimeHandshake",
    "ConstitutionError",
    "ConstitutionGuidance",
    "ConstitutionIntegrityError",
    "ConstitutionManifest",
    "ConstitutionNotFoundError",
    "ConstitutionPackage",
    "ConstitutionPackageError",
    "ConstitutionPackageNotFoundError",
    "ConstitutionPackageRegistry",
    "ConstitutionRef",
    "ConstitutionResolver",
    "ConstitutionSource",
    "ConstitutionSummary",
    "EvidenceRef",
    "FileConstitutionResolver",
    "KnowledgePacket",
    "Ledger",
    "MethodRef",
    "ProviderConstraint",
    "RuntimeCompatibility",
    "SignedPacket",
    "constraints_by_precedence",
    "default_registry",
    "derive_agent_id",
    "PublicResearchIndex",
    "ResearchIndexBackend",
    "PUBLICATION_SCHEMA",
    "PUBLICATION_STATE_SCHEMA",
    "PublicationService",
    "PublicationBackend",
    "decode_adoption_request",
    "decode_runtime_handshake",
    "encode_adoption_request",
    "encode_runtime_handshake",
    "merge_constraints",
    "sign_packet",
    "export_public_snapshot",
    "import_public_snapshot",
    "load_public_snapshot",
    "search_public_snapshot",
    "ProtocolNotFoundError",
    "load_schema",
    "protocol_ids",
    "schema_path",
    "version_key",
]

__version__ = "0.1.0"
